services:
    localstack:
        name: localstack
        triggeredBy:
            - postEnvironmentStart
        commands:
            start: ACTIVATE_PRO=0 localstack start
            stop: localstack stop